on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      
      - name: Get dependencies
        run: go get -v -t -d ./...
      
      - name: Build
        run: go build -v ./...
      
      - name: Test
        run: go test -v ./...

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/k8s-openstack-pv-exporter:${{ github.sha }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to ghcr.io
        run: docker push ghcr.io/${{ github.repository_owner }}/k8s-openstack-pv-exporter:${{ github.sha }}

      - name: Verify Published Image
        run: docker pull ghcr.io/${{ github.repository_owner }}/k8s-openstack-pv-exporter:${{ github.sha }}
