on:
  push:
    branches:
      - main
    tags:
    - 'v*.*.*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: drumato
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tags
        id: docker_tag
        run: |

          echo "sha_tag=${{ github.sha }}" >> $GITHUB_ENV
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then

            tag="${{ github.ref }}"
            tag=${tag/refs\/tags\//}
            echo "release_tag=$tag" >> $GITHUB_ENV
          else
            echo "release_tag=" >> $GITHUB_ENV
          fi

      - name: Build and push Docker Image to ghcr.io
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/drumato/k8s-openstack-pv-exporter:${{ env.sha_tag }}
          platforms: linux/amd64,linux/arm64


      - name: Add release tag if available
        if: env.release_tag != ''
        run: |
          docker tag ghcr.io/drumato/k8s-openstack-pv-exporter:${{ env.sha_tag }} ghcr.io/drumato/k8s-openstack-pv-exporter:${{ env.release_tag }}
          docker push ghcr.io/drumato/k8s-openstack-pv-exporter:${{ env.release_tag }}
